# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwhhrBSzAGltVLlxMeI6HW-i6p6gxP4m
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/summer/WA_Fn-UseC_-Telco-Customer-Churn.csv')

df.head()

print("Missing Values:")
print(df.isnull().sum())

df = df.dropna()

print("Missing values removed successfully")

print("Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicate records removed successfully")

print("Dataset Shape:", df.shape)

plt.figure(figsize=(6,4))
plt.boxplot(df['MonthlyCharges'])
plt.title("Outlier Detection - Monthly Charges")
plt.show()

plt.figure(figsize=(6,4))
plt.boxplot(df['tenure'])
plt.title("Outlier Detection - Tenure")
plt.show()

df.info()