# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZwtgHMkgKI8Abn4DE1bc6zSN77jQf9Vi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/summer/WA_Fn-UseC_-Telco-Customer-Churn.csv')

df.head()

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

df.info()

df.describe()

df.isnull().sum()

df['Churn'].value_counts()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df['Churn'].value_counts().plot(kind='bar')

plt.title("Customer Churn Distribution")
plt.xlabel("Churn")
plt.ylabel("Count")

plt.show()

df['MonthlyCharges'].hist(bins=20)

plt.title("Monthly Charges Distribution")
plt.xlabel("Monthly Charges")
plt.ylabel("Frequency")

plt.show()

df['tenure'].hist(bins=20)

plt.title("Tenure Distribution")
plt.xlabel("Tenure")
plt.ylabel("Frequency")

plt.show()