# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ve2_G20U_gQ7pThIhsUrJm7vaCmHkTxq
"""

# Step 01: Data Loading
# Customer Churn Prediction & Retention Framework

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Upload dataset from computer
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")   # change file name if different

# Display first 5 rows
df.head()

# Verify dataset
print("Dataset Shape:", df.shape)
print("Columns:", df.columns)

df.info()

# Check missing values
df.isnull().sum()

# Backup dataset
df_backup = df.copy()

print("Backup created successfully")