# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZyMY4feNs6Bx2rxtlPm_TMQVHRn-W6f
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/summer/WA_Fn-UseC_-Telco-Customer-Churn.csv')

df.head()

df['Churn'].value_counts().plot(kind='bar')

plt.title("Customer Churn Distribution")
plt.xlabel("Churn")
plt.ylabel("Count")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['MonthlyCharges'], bins=20)

plt.title("Monthly Charges Distribution")
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['tenure'], bins=20)

plt.title("Tenure Distribution")
plt.show()

sns.countplot(x='gender', hue='Churn', data=df)

plt.title("Gender vs Churn")
plt.show()

sns.countplot(x='Contract', hue='Churn', data=df)

plt.xticks(rotation=20)

plt.title("Contract Type vs Churn")
plt.show()

numeric_df = df.select_dtypes(include=['int64','float64'])

plt.figure(figsize=(10,8))

sns.heatmap(numeric_df.corr(),
            annot=True,
            cmap='coolwarm')

plt.title("Correlation Matrix")
plt.show()

sns.boxplot(x='Churn', y='MonthlyCharges', data=df)

plt.title("Monthly Charges vs Churn")
plt.show()

sns.boxplot(x='Churn', y='tenure', data=df)

plt.title("Tenure vs Churn")
plt.show()