# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYnCACPIqdRU1rIthxAJmgZgcKojnSB1

Basic code
"""

print("hello world")

"""basic maths"""

name = input("Enter your name: ")

print("Welcome", name)

name = "Dhanesh"
age = 21

print(name)
print(age)

a = 10
b = 20

c = a + b

print("Sum =", c)

age = 21

if age >= 18:
    print("Eligible to Vote")
else:
    print("Not Eligible")

for i in range(1, 6):
    print(i)

i = 1

while i <= 5:
    print(i)
    i += 1

fruits = ["Apple", "Banana", "Mango"]

print(fruits)
print(fruits[0])

student = {
    "Name": "Dhanesh",
    "Age": 21,
    "Branch": "CSE"
}

print(student)
print(student["Name"])

def greet():
    print("Hello Student")

greet()

def add(a, b):
    return a + b

result = add(10, 20)

print(result)

import math

print(math.sqrt(25))

import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)

import pandas as pd

data = {
    "Name": ["Ram", "Shyam", "Ravi"],
    "Age": [20, 21, 22]
}

df = pd.DataFrame(data)

print(df)

import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y = [10,20,30,40,50]

plt.plot(x, y)
plt.show()

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/summer/WA_Fn-UseC_-Telco-Customer-Churn.csv")

import matplotlib.pyplot as plt

subjects = ["Python", "Java", "C++"]
marks = [80, 70, 90]

plt.bar(subjects, marks)
plt.show()

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

print("Model Created Successfully")